---
abstract: 'hierachical (array based) objects'
author:
  - 'Mike Würfel <sknpp@cpan.org>'
build_requires:
  Package::Subroutine: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HO-common
provides:
  HO::ClassBuilder:
    file: lib/HO/ClassBuilder.pm
    version: '0.001'
requires:
  Class::Data::Localize: '0.0401'
  HO::class: '0.076'
  parent: '0'
  perl: '5.008'
resources:
  homepage: http://github.com/giftnuss/p5-ho-common/tree/master
  repository: git://github.com/giftnuss/p5-ho-common.git
version: '0.68'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
